sut:
    build: .
    command: sh -c "npm test && ./tests/rest_api.sh"
    volumes:
     - ./src:/home/app/code/src
     - ./tests:/home/app/code/tests
     - ./index.js:/home/app/code/index.js
     - ./config.js:/home/app/code/config.js
    links:
     - app
    environment:
     - "API_SECRET=1234"
     - "BASE_URL=http://app:8000"
     - "LOG_LEVEL=error"
     - "NODE_ENV="

app:
    build: .
    command: node index.js | ./node_modules/.bin/bunyan -l 0
    volumes:
     - ./src:/home/app/code/src
     - ./tests:/home/app/code/tests
     - ./index.js:/home/app/code/index.js
     - ./config.js:/home/app/code/config.js
    ports:
     - "8000:8000"
    environment:
     - "API_SECRET=1234"
     - "LOG_LEVEL=info"
     - "NODE_ENV="
